# -*- coding: utf-8 -*-
"""nlp_colab_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbUiemzBOh27ymWOa0tv-Auz6x-fdaRj

***Integrantes:** Jhoan Avila Gutierrez; Freddy Forero Rojas; Harold Duque Castañeda*<br>
***Clase:** Procesamiento Lenguaje Natural*<br>
***Programa:** Esp. Inteligencia Artificial, Universidad de Cundinamarca*

# 🚀 Laboratorio de Procesamiento de Texto (NLP)

Este notebook contiene la implementación de los conceptos solicitados en la actividad para el procesamiento de texto:

**Primer Bloque:**
1. Normalización de Texto
2. Stemming
3. Stopwords
4. Term Frequency
5. Inverse Document Frequency
6. Part-of-Speech Tagging
7. Lematización
8. Parsing Sintáctico
9. Named-Entity

**Segundo Bloque:**
1. Generacion de texto usando LLM

**Tercer Bloque:**
1. Text Classification
2. Question Answering
3. Summarization
4. Sentence Similarity
5. Translation
6. Text Generation
7. Text mining

## 📦 0. Instalación y Configuración del Entorno
Ejecutar la siguiente celda para instalar y descargar los paquetes necesarios en el ambiente local (`NLTK`, `SpaCy`, `Scikit-Learn`, `Pandas`, etc.).
"""

# Instalación de librerías en Google Colab
!pip install -q nltk spacy scikit-learn pandas gensim matplotlib

import nltk
import spacy
from spacy import displacy
import pandas as pd
import numpy as np
import re
import unicodedata
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Descarga de recursos de NLTK
resources = ['punkt', 'stopwords', 'wordnet', 'averaged_perceptron_tagger']
for r in resources:
    try:
        nltk.download(r, quiet=True)
    except Exception as e:
        print(f"Error descargando {r}: {e}")

# Descarga de modelo SpaCy en español
try:
    nlp_es = spacy.load("es_core_news_sm")
except OSError:
    !python -m spacy download es_core_news_sm
    nlp_es = spacy.load("es_core_news_sm")

print("✅ Entorno de NLP configurado exitosamente.")

"""## ⚙️ Configuración Primer Bloque: `Class NLPProcesadorTexto`
1. Ingresamos el texto que sera procesado por cada funcion.
2. Encapsulamos todas las funciones de procesamiento de texto del primer bloque en una clase estructurada.
"""

texto_a_procesar = """
El grave incendio forestal en Villa de Leyva (Boyacá), iniciado el pasado sábado diecinueve de septiembre
en la vereda La Castellana y el cerro San Marcos, ha consumido más de 1340 hectáreas de vegetación nativa y pino,
afectando gravemente zonas de acuíferos, senderos turísticos y forzando la suspensión temporal de clases.
Las autoridades, que reportan un control del fuego cercano al 78%, sospechan que la emergencia fue provocada
por manos criminales, por lo que la Gobernación de Boyacá ha ofrecido una recompensa de hasta cuarenta y cinco millones
de pesos por información de los responsables mientras los cuerpos de socorro y helicópteros continúan extinguiendo
los focos activos.
"""

class NLPProcesadorTexto:
    def __init__(self, lang="es"):
        self.lang = lang
        nltk_lang = 'spanish' if self.lang == 'es' else 'english'
        self.stemmer = nltk.stem.SnowballStemmer(nltk_lang)
        self.nltk_stopwords = set(nltk.corpus.stopwords.words(nltk_lang))
        model_name = "es_core_news_sm" if self.lang == "es" else "en_core_web_sm"
        self.nlp = spacy.load(model_name)

    # 1. Normalización
    def normalizar_texto(self, texto, remover_acentos=True, remover_numeros=False, minusculas=True):
        if minusculas:
            texto = texto.lower()
        if remover_acentos:
            texto = unicodedata.normalize('NFD', texto)
            texto = ''.join([c for c in texto if unicodedata.category(c) != 'Mn'])
        if remover_numeros:
            texto = re.sub(r'\d+', '', texto)
        texto = re.sub(r'[^\w\s]', '', texto)
        return re.sub(r'\s+', ' ', texto).strip()

    # 2. Stemming
    def stemming_texto(self, tokens):
        if isinstance(tokens, str):
            tokens = re.findall(r'\b\w+\b', tokens)
        return [(t, self.stemmer.stem(t)) for t in tokens]

    # 3. Stopwords
    def remover_stopwords(self, tokens, adicionales=None):
        stops = set(self.nltk_stopwords).union(self.nlp.Defaults.stop_words)
        if adicionales:
            stops.update([a.lower() for a in adicionales])
        return [t for t in tokens if t.lower() not in stops and len(t) > 1]

    # 4. Term Frequency (TF)
    def calcular_tf(self, corpus):
        vectorizer = CountVectorizer()
        matriz = vectorizer.fit_transform(corpus)
        return pd.DataFrame(matriz.toarray(), columns=vectorizer.get_feature_names_out(), index=[f'Texto_{i+1}' for i in range(len(corpus))])

    # 5. TF-IDF & IDF
    def calcular_tfidf(self, corpus):
        vectorizer = TfidfVectorizer()
        matriz = vectorizer.fit_transform(corpus)
        df_tfidf = pd.DataFrame(matriz.toarray(), columns=vectorizer.get_feature_names_out(), index=[f'Texto_{i+1}' for i in range(len(corpus))])
        df_idf = pd.DataFrame({'Palabra': vectorizer.get_feature_names_out(), 'IDF': vectorizer.idf_}).sort_values('IDF', ascending=False)
        return df_tfidf, df_idf

    # 6. POS Tagging
    def etiquetar_pos(self, texto):
        doc = self.nlp(texto)
        return pd.DataFrame([{'Token': t.text, 'POS': t.pos_, 'Tag': t.tag_, 'Explicacion': spacy.explain(t.pos_)} for t in doc if not t.is_space])

    # 7. Lematización
    def lematizar(self, texto):
        doc = self.nlp(texto)
        return pd.DataFrame([{'Token': t.text, 'Lema': t.lemma_, 'POS': t.pos_} for t in doc if not t.is_space and not t.is_punct])

    # 8. Parsing Sintáctico
    def parsing_sintactico(self, texto):
        doc = self.nlp(texto)
        return pd.DataFrame([{'Token': t.text, 'Dep': t.dep_, 'Explicacion': spacy.explain(t.dep_), 'Head': t.head.text} for t in doc if not t.is_space])

    def visualizar_parsing(self, texto):
        doc = self.nlp(texto)
        displacy.render(doc, style="dep", jupyter=True, options={"distance": 100, "color": "#0284c7", "bg": "#f8fafc"})

    # 9. NER
    def reconocer_entidades(self, texto):
        doc = self.nlp(texto)
        return pd.DataFrame([{'Entidad': e.text, 'Etiqueta': e.label_, 'Explicacion': spacy.explain(e.label_)} for e in doc.ents])

    def visualizar_ner(self, texto):
        doc = self.nlp(texto)
        displacy.render(doc, style="ent", jupyter=True)

# Instanciamos el procesador en español
nlp = NLPProcesadorTexto(lang="es")
print("✅ Clase NLPProcesadorTexto esta lista para usarse.")

"""---
## 🛠️ 1. Normalización de Texto
La **normalización** transforma el texto crudo en un formato uniforme y limpio eliminando variaciones tipográficas, signos de puntuación, mayúsculas y acentos.
"""

#texto_ejemplo = "¡Hola Mundo! Este es un Ejemplo de Normalización (¡con Ácentós y Números 2026!)."
texto_limpio = nlp.normalizar_texto(texto_a_procesar)

print("🔴 Texto Original :", texto_a_procesar)
print("🟢 Texto Normalizado:", texto_limpio)

"""---
## 🌾 2. Stemming
El **Stemming** recorta los sufijos de las palabras para obtener la raíz morfológica común (stem). Es un proceso heurístico basado en reglas de sufijo.
"""

#palabras_ejemplo = ["corriendo", "correrá", "corredor", "jugadores", "jugando", "computadoras", "computación"]

stems = nlp.stemming_texto(texto_a_procesar)
df_stems = pd.DataFrame(stems, columns=["Palabra Original", "Stem (Raíz)"])
display(df_stems)

"""---
## 🛑 3. Stopwords (Palabras Vacías)
Las **Stopwords** son palabras altamente frecuentes (artículos, preposiciones, conjunciones) que aportan poco valor semántico en tareas de análisis.
"""

#frase = ["el", "gato", "está", "durmiendo", "tranquilamente", "sobre", "el", "sofá", "de", "la", "casa"]
sin_stopwords = nlp.remover_stopwords(texto_limpio.split())

print("🔴 Texto Original :", texto_a_procesar)
print("🟢 Texto sin Stopwords:", sin_stopwords)

"""---
## 📊 4. Term Frequency (TF)
Mide la frecuencia con la que un término o palabra aparece en un conjunto de documentos.
"""

corpus = [
    texto_a_procesar,
    "El incendio forestal en Villa de Leyva.",
    "La Gobernación de Boyacá ha ofrecido una recompensa."
]

df_tf = nlp.calcular_tf(corpus)
display(df_tf)

"""---
## 📈 5. Inverse Document Frequency (IDF / TF-IDF)
El **TF-IDF** penaliza palabras comunes a través de todos los documentos y destaca términos específicos de cada documento.
"""

df_tfidf, df_idf = nlp.calcular_tfidf(corpus)

print("Matriz TF-IDF")
display(df_tfidf)

print("\n TOP 10 Inverse Document Frequency (Mayor IDF = Términos más raros/específicos)")
df_idf_order = df_idf.sort_values(by="IDF", ascending=True)
display(df_idf_order.head(10))

"""---
## 🏷️ 6. Part-of-Speech (POS) Tagging
El **POS Tagging** clasifica cada palabra en una categoría gramatical (Sustantivo, Verbo, Adjetivo, Adverbio, etc.).
"""

#texto_pos = "Los talentosos científicos desarrollan innovadores modelos matemáticos velozmente."
df_pos = nlp.etiquetar_pos(texto_a_procesar)
display(df_pos)

"""---
## 🌿 7. Lematización
A diferencia del Stemming, la **Lematización** encuentra la forma gramatical canónica de una palabra (lema) utilizando vocabularios y análisis morfológico.
"""

#texto_lem = "Los gatos estaban corriendo rápidamente y rompieron los jarrones de la mesa."
df_lem = nlp.lematizar(texto_a_procesar)
display(df_lem)

"""---
## 🌳 8. Parsing (Dependency Parsing)
El **Parsing** analiza las relaciones sintácticas en la oración identificando el verbo principal (raíz), sujeto, objeto directo y modificadores dependientes.
"""

texto_parse = "El grave incendio forestal en Villa de Leyva iniciado el pasado sábado diecinueve de septiembre ha consumido más de 1340 hectáreas de vegetación nativa y pino"

# 1. Tabla de dependencias
df_parse = nlp.parsing_sintactico(texto_a_procesar)
display(df_parse)

# 2. Visualización interactiva con displaCy
print("\n--- Visualización Parsing del Árbol Sintáctico ---")
nlp.visualizar_parsing(texto_parse)

"""---
## 🔍 9. Named-Entity Recognition (NER)
**NER** reconoce e identifica entidades nombradas en el texto (Personas, Organizaciones, Lugares, Fechas, Monedas, etc.).
"""

texto_ner = "El grave incendio forestal en Villa de Leyva (Boyaca) iniciado el pasado sábado diecinueve de septiembre ha consumido más de 1340 hectáreas de vegetación nativa y pino. Reporta BBC Noticias."

# 1. Tabla de Entidades
df_ner = nlp.reconocer_entidades(texto_a_procesar)
display(df_ner)

# 2. Visualización destacada con displaCy
print("\n--- Visualización de Entidades Nombradas (NER) ---")
nlp.visualizar_ner(texto_ner)

"""---
## ⚙️ Segundo Bloque: `Large language Models`

## 🏆 9. Generación de texto usando LLM
## Objetivo

Desarrollar un sistema de generación de texto utilizando un modelo
de lenguaje grande (LLM) mediante una API en la nube, aplicando
principios básicos de MLOps para el manejo de datos, consumo del
modelo, registro de resultados y monitoreo.

## Flujo del proyecto

1. Preparación y manejo de datos.
2. Configuración del entorno.
3. Conexión con un LLM mediante API.
4. Generación de texto.
5. Registro de resultados.
6. Monitoreo del sistema.
7. Evaluación de resultados.
"""

# Instalación de dependencias

!pip install -q openai pandas matplotlib seaborn

# Importación de librerías

import os
import time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from openai import OpenAI

print("Librerías cargadas correctamente.")

# Crear dataset de prompts

datos = {
    "id": [1, 2, 3, 4, 5],
    "categoria": [
        "tecnologia",
        "educacion",
        "turismo",
        "salud",
        "medio_ambiente"
    ],
    "prompt": [
        "Explica qué es la inteligencia artificial en palabras sencillas.",
        "Explica por qué es importante aprender programación.",
        "Describe tres lugares turísticos interesantes de Colombia.",
        "Explica de forma general la importancia de dormir bien.",
        "Explica tres formas de reducir la contaminación ambiental."
    ]
}

df = pd.DataFrame(datos)

print("Dataset creado correctamente.")
df

# Revisión básica del dataset

print("Número de registros:", len(df))
print("\nValores nulos:")
print(df.isnull().sum())

print("\nRegistros duplicados:", df.duplicated().sum())

print("\nTipos de datos:")
print(df.dtypes)

# Guardar dataset original

df.to_csv("dataset_prompts.csv", index=False)

print("Dataset guardado como dataset_prompts.csv")

!pip install -q google-genai

from google.colab import userdata
from google import genai

# Obtener API Key de forma segura
gemini_api_key = userdata.get("GEMINI_API_KEY")

if gemini_api_key:
    print("API Key de Gemini cargada correctamente.")
else:
    print("No se encontró la API Key.")

# Crear cliente de Gemini
client = genai.Client(api_key=gemini_api_key)

print("Cliente de Gemini configurado correctamente.")

# Consultar modelos disponibles

modelos_disponibles = []

for model in client.models.list():
    if "generateContent" in model.supported_actions:
        modelos_disponibles.append(model.name)

print("Modelos disponibles para generación de texto:\n")

for modelo in modelos_disponibles:
    print(modelo)

# Primera generación de texto con Gemini 3.8 Flash

prompt = df.loc[0, "prompt"]

response = client.models.generate_content(
    model="gemini-3.8-flash",
    contents=prompt
)

respuesta = response.text

print("PROMPT:")
print(prompt)

print("\nRESPUESTA DEL MODELO:")
print(respuesta)

import time

def generar_respuesta(prompt, max_intentos=3):
    """
    Genera una respuesta utilizando Gemini 3.8 Flash.
    Incluye reintentos y medición del tiempo de respuesta.
    """

    for intento in range(1, max_intentos + 1):

        inicio = time.time()

        try:
            response = client.models.generate_content(
                model="gemini-3.8-flash",
                contents=prompt
            )

            tiempo_respuesta = time.time() - inicio

            return {
                "respuesta": response.text,
                "tiempo_segundos": round(tiempo_respuesta, 2),
                "intentos": intento,
                "estado": "exitoso",
                "error": None
            }

        except Exception as e:

            tiempo_respuesta = time.time() - inicio

            print(f"Intento {intento} fallido: {e}")

            if intento < max_intentos:
                # Esperar antes de volver a intentar
                tiempo_espera = 2 ** intento
                print(f"Reintentando en {tiempo_espera} segundos...")
                time.sleep(tiempo_espera)

            else:
                return {
                    "respuesta": None,
                    "tiempo_segundos": round(tiempo_respuesta, 2),
                    "intentos": intento,
                    "estado": "fallido",
                    "error": str(e)
                }

resultado = generar_respuesta(
    "Explica brevemente qué es el aprendizaje automático."
)

print("Estado:", resultado["estado"])
print("Tiempo:", resultado["tiempo_segundos"], "segundos")
print("Intentos:", resultado["intentos"])

print("\nRespuesta:")
print(resultado["respuesta"])

# Procesar todos los prompts del dataset

resultados = []

for _, fila in df.iterrows():

    print(f"Procesando registro {fila['id']}...")

    resultado = generar_respuesta(fila["prompt"])

    resultados.append({
        "id": fila["id"],
        "categoria": fila["categoria"],
        "prompt": fila["prompt"],
        "respuesta": resultado["respuesta"],
        "tiempo_segundos": resultado["tiempo_segundos"],
        "intentos": resultado["intentos"],
        "estado": resultado["estado"],
        "error": resultado["error"]
    })

print("\nProcesamiento terminado.")

# Crear DataFrame con los resultados

df_resultados = pd.DataFrame(resultados)

df_resultados

# Resumen de ejecución

print("Total de solicitudes:", len(df_resultados))

print("\nEstados:")
print(df_resultados["estado"].value_counts())

print("\nTiempo promedio:")
print(round(df_resultados["tiempo_segundos"].mean(), 2), "segundos")

print("\nNúmero total de intentos:")
print(df_resultados["intentos"].sum())

# Guardar registro de ejecuciones

df_resultados.to_csv("registro_ejecuciones.csv", index=False)

print("Registro guardado como registro_ejecuciones.csv")

# Monitoreo: estado de las solicitudes

estados = df_resultados["estado"].value_counts()

print("Resumen de solicitudes:")
print(estados)

print("\nPorcentaje de éxito:")

exitosas = (df_resultados["estado"] == "exitoso").sum()
total = len(df_resultados)

porcentaje_exito = (exitosas / total) * 100

print(f"{porcentaje_exito:.2f}%")

# Estadísticas de tiempo de respuesta

print("Tiempo mínimo:",
      df_resultados["tiempo_segundos"].min(), "segundos")

print("Tiempo máximo:",
      df_resultados["tiempo_segundos"].max(), "segundos")

print("Tiempo promedio:",
      round(df_resultados["tiempo_segundos"].mean(), 2), "segundos")

# Gráfica de tiempos de respuesta

plt.figure(figsize=(8, 5))

plt.bar(
    df_resultados["id"],
    df_resultados["tiempo_segundos"]
)

plt.xlabel("ID de solicitud")
plt.ylabel("Tiempo de respuesta (segundos)")
plt.title("Tiempo de respuesta del LLM")

plt.show()

# Gráfica de solicitudes por estado

plt.figure(figsize=(6, 4))

df_resultados["estado"].value_counts().plot(kind="bar")

plt.xlabel("Estado")
plt.ylabel("Número de solicitudes")
plt.title("Estado de las solicitudes al LLM")

plt.show()

# Evaluación básica de las respuestas

def evaluar_respuesta(respuesta):
    if respuesta is None:
        return {
            "longitud_caracteres": 0,
            "numero_palabras": 0,
            "respuesta_valida": False
        }

    numero_palabras = len(respuesta.split())
    longitud_caracteres = len(respuesta)

    return {
        "longitud_caracteres": longitud_caracteres,
        "numero_palabras": numero_palabras,
        "respuesta_valida": numero_palabras >= 10
    }

# Aplicar evaluación a todas las respuestas

metricas = df_resultados["respuesta"].apply(evaluar_respuesta)

df_metricas = pd.DataFrame(metricas.tolist())

df_resultados = pd.concat(
    [df_resultados, df_metricas],
    axis=1
)

df_resultados

# Resumen de calidad

print("Promedio de palabras por respuesta:",
      round(df_resultados["numero_palabras"].mean(), 2))

print("Promedio de caracteres por respuesta:",
      round(df_resultados["longitud_caracteres"].mean(), 2))

respuestas_validas = df_resultados["respuesta_valida"].sum()

print(
    f"Respuestas que cumplen el criterio: "
    f"{respuestas_validas}/{len(df_resultados)}"
)

# Visualización de longitud de respuestas

plt.figure(figsize=(8, 5))

plt.bar(
    df_resultados["id"],
    df_resultados["numero_palabras"]
)

plt.xlabel("ID de solicitud")
plt.ylabel("Número de palabras")
plt.title("Longitud de las respuestas generadas")

plt.show()

# Guardar resultados finales

df_resultados.to_csv(
    "resultados_finales_llm.csv",
    index=False
)

print("Resultados guardados correctamente.")
print("Archivo: resultados_finales_llm.csv")

# Resumen final del experimento

total_solicitudes = len(df_resultados)

solicitudes_exitosas = (
    df_resultados["estado"] == "exitoso"
).sum()

porcentaje_exito = (
    solicitudes_exitosas / total_solicitudes
) * 100

tiempo_promedio = df_resultados[
    "tiempo_segundos"
].mean()

palabras_promedio = df_resultados[
    "numero_palabras"
].mean()

print("========== RESUMEN DEL EXPERIMENTO ==========")

print(f"Total de solicitudes: {total_solicitudes}")
print(f"Solicitudes exitosas: {solicitudes_exitosas}")
print(f"Porcentaje de éxito: {porcentaje_exito:.2f}%")
print(f"Tiempo promedio: {tiempo_promedio:.2f} segundos")
print(f"Palabras promedio por respuesta: {palabras_promedio:.2f}")

print("==============================================")

"""# Arquitectura del proyecto

El proyecto utiliza Google Colab como entorno de ejecución y un
modelo LLM alojado en la nube mediante una API.

### Flujo del sistema

Usuario / Dataset
       ↓
Google Colab
       ↓
Validación y procesamiento de datos
       ↓
API de Gemini
       ↓
Gemini 3.8 Flash
       ↓
Generación de texto
       ↓
Registro de resultados
       ↓
Monitoreo y evaluación

### Componentes MLOps

- **Datos:** dataset de prompts almacenado en CSV.
- **Modelo:** Gemini 3.8 Flash mediante API.
- **Infraestructura:** Google Colab + servicio de IA en la nube.
- **Registro:** prompts, respuestas, tiempos, estados e intentos.
- **Monitoreo:** porcentaje de éxito y tiempo de respuesta.
- **Evaluación:** longitud y cantidad de palabras de las respuestas.

# Conclusiones

Durante esta práctica se desarrolló un sistema de generación de texto
utilizando un modelo de lenguaje grande (LLM) mediante una API en la nube.

Se realizó un manejo básico de los datos mediante un dataset de prompts,
validando registros y almacenándolos en formato CSV.

El modelo Gemini 3.8 Flash fue utilizado como servicio en la nube,
permitiendo generar respuestas sin ejecutar el modelo localmente.

También se implementó un registro de las ejecuciones, incluyendo el
tiempo de respuesta, número de intentos, estado de la solicitud y
posibles errores.

Finalmente, se implementaron métricas y visualizaciones para monitorear
el funcionamiento del sistema y evaluar características básicas de las
respuestas generadas.

La práctica permitió aplicar conceptos básicos de MLOps a un sistema
basado en LLM, integrando datos, modelo, infraestructura, monitoreo y
evaluación.

---
## ⚙️ Tercer Bloque: `Dataset Youtube Statistics`

## 📦 Descarga de Dataset
Ejecutar la siguiente celda para instalar y descargar el datasets de Youtube Statistics.
"""

# Instalación de KaggleHub
!pip install -q kagglehub

import kagglehub
import pandas as pd
from pathlib import Path

# Descarga automática del dataset
ruta_dataset = Path(
    kagglehub.dataset_download("advaypatil/youtube-statistics")
)

print("Dataset descargado en:", ruta_dataset)
print("Archivos encontrados:")

for archivo in ruta_dataset.iterdir():
    print("-", archivo.name)

## 📊 Exploración inicial del conjunto de datos

# Construir las rutas de los archivos
ruta_videos = ruta_dataset / "videos-stats.csv"
ruta_comentarios = ruta_dataset / "comments.csv"

# Cargar los archivos
df_videos = pd.read_csv(ruta_videos)
df_comentarios = pd.read_csv(ruta_comentarios)

# Mostrar dimensiones
print("Dimensión de videos:", df_videos.shape)
print("Dimensión de comentarios:", df_comentarios.shape)

# Mostrar nombres de columnas
print("\nColumnas de videos:")
print(df_videos.columns.tolist())

print("\nColumnas de comentarios:")
print(df_comentarios.columns.tolist())

# Visualizar ejemplos
print("\nPrimeros registros de videos:")
display(df_videos.head())

print("\nPrimeros registros de comentarios:")
display(df_comentarios.head())

## 🧹 Preparación y limpieza de los datos

# Crear copias para conservar los datos originales
videos_limpios = df_videos.copy()
comentarios_limpios = df_comentarios.copy()

# Eliminar columnas de índice innecesarias
videos_limpios.drop(columns=["Unnamed: 0"], errors="ignore", inplace=True)
comentarios_limpios.drop(columns=["Unnamed: 0"], errors="ignore", inplace=True)

# Limpiar identificadores y textos
videos_limpios["Video ID"] = (
    videos_limpios["Video ID"]
    .astype("string")
    .str.strip()
)

comentarios_limpios["Video ID"] = (
    comentarios_limpios["Video ID"]
    .astype("string")
    .str.strip()
)

comentarios_limpios["Comment"] = (
    comentarios_limpios["Comment"]
    .astype("string")
    .str.strip()
)

# Convertir las columnas numéricas
for columna in ["Likes", "Comments", "Views"]:
    videos_limpios[columna] = pd.to_numeric(
        videos_limpios[columna],
        errors="coerce"
    )

for columna in ["Likes", "Sentiment"]:
    comentarios_limpios[columna] = pd.to_numeric(
        comentarios_limpios[columna],
        errors="coerce"
    )

# Eliminar registros sin identificador o sin comentario
videos_limpios.dropna(subset=["Video ID"], inplace=True)
comentarios_limpios.dropna(
    subset=["Video ID", "Comment"],
    inplace=True
)

# Eliminar comentarios vacíos
comentarios_limpios = comentarios_limpios[
    comentarios_limpios["Comment"].str.len() > 0
]

# Eliminar duplicados
videos_limpios.drop_duplicates(
    subset=["Video ID"],
    inplace=True
)

comentarios_limpios.drop_duplicates(
    subset=["Video ID", "Comment"],
    inplace=True
)

# Etiquetas del sentimiento:
# 0 = negativo, 1 = neutral, 2 = positivo
mapa_sentimientos = {
    0: "Negativo",
    1: "Neutral",
    2: "Positivo"
}

comentarios_limpios["Sentimiento texto"] = (
    comentarios_limpios["Sentiment"]
    .map(mapa_sentimientos)
    .fillna("Desconocido")
)

# Características básicas de cada comentario
comentarios_limpios["Cantidad caracteres"] = (
    comentarios_limpios["Comment"].str.len()
)

comentarios_limpios["Cantidad palabras"] = (
    comentarios_limpios["Comment"].str.split().str.len()
)

# Mostrar resultados
print("Videos después de la limpieza:", videos_limpios.shape)
print("Comentarios después de la limpieza:", comentarios_limpios.shape)

print("\nDistribución de sentimientos:")
display(
    comentarios_limpios["Sentimiento texto"]
    .value_counts()
    .rename_axis("Sentimiento")
    .reset_index(name="Cantidad")
)

print("\nEjemplo de comentarios procesados:")
display(
    comentarios_limpios[
        [
            "Video ID",
            "Comment",
            "Likes",
            "Sentimiento texto",
            "Cantidad palabras"
        ]
    ].head()
)

## 🔗 Integración de comentarios y estadísticas por video


# Resumen numérico de comentarios por video
resumen_comentarios = (
    comentarios_limpios
    .groupby("Video ID")
    .agg(
        Comentarios_disponibles=("Comment", "count"),
        Likes_comentarios_total=("Likes", "sum"),
        Likes_comentarios_promedio=("Likes", "mean"),
        Palabras_promedio=("Cantidad palabras", "mean"),
        Caracteres_promedio=("Cantidad caracteres", "mean"),
        Sentimiento_promedio=("Sentiment", "mean")
    )
    .reset_index()
)

# Calcular proporciones de sentimiento por video
proporciones_sentimiento = pd.crosstab(
    comentarios_limpios["Video ID"],
    comentarios_limpios["Sentimiento texto"],
    normalize="index"
).reset_index()

# Garantizar que existan las tres columnas
for sentimiento in ["Negativo", "Neutral", "Positivo"]:
    if sentimiento not in proporciones_sentimiento.columns:
        proporciones_sentimiento[sentimiento] = 0.0

# Renombrar las proporciones
proporciones_sentimiento.rename(
    columns={
        "Negativo": "Proporcion_negativos",
        "Neutral": "Proporcion_neutrales",
        "Positivo": "Proporcion_positivos"
    },
    inplace=True
)

# Construir un contexto textual por video
textos_por_video = (
    comentarios_limpios
    .groupby("Video ID")["Comment"]
    .apply(lambda comentarios: " ".join(comentarios.astype(str)))
    .reset_index(name="Texto_comentarios")
)

# Integrar los resúmenes de comentarios
resumen_comentarios = resumen_comentarios.merge(
    proporciones_sentimiento[
        [
            "Video ID",
            "Proporcion_negativos",
            "Proporcion_neutrales",
            "Proporcion_positivos"
        ]
    ],
    on="Video ID",
    how="left"
)

resumen_comentarios = resumen_comentarios.merge(
    textos_por_video,
    on="Video ID",
    how="left"
)

# Unir los comentarios con las estadísticas de los videos
datos_youtube = videos_limpios.merge(
    resumen_comentarios,
    on="Video ID",
    how="inner"
)

# Crear una variable transformada para las visualizaciones y el futuro modelo
datos_youtube["Log_Views"] = np.log1p(datos_youtube["Views"])

# Redondear variables para una presentación más clara
columnas_redondear = [
    "Likes_comentarios_promedio",
    "Palabras_promedio",
    "Caracteres_promedio",
    "Sentimiento_promedio",
    "Proporcion_negativos",
    "Proporcion_neutrales",
    "Proporcion_positivos"
]

datos_youtube[columnas_redondear] = (
    datos_youtube[columnas_redondear].round(3)
)

# Resultados de la integración
print("Videos originales después de limpieza:", len(videos_limpios))
print("Videos con comentarios asociados:", len(datos_youtube))
print("Cantidad de columnas finales:", datos_youtube.shape[1])

print("\nEjemplo del conjunto integrado:")

display(
    datos_youtube[
        [
            "Video ID",
            "Title",
            "Views",
            "Comentarios_disponibles",
            "Likes_comentarios_promedio",
            "Proporcion_negativos",
            "Proporcion_neutrales",
            "Proporcion_positivos"
        ]
    ].head()
)

"""## ❓ 10. Question Answering

Question Answering permite formular una pregunta sobre un texto y extraer una respuesta directamente del contexto proporcionado. En este ejercicio se utilizarán los comentarios asociados a un video como contexto.

Debido a que los comentarios del conjunto de datos están escritos principalmente en inglés, se utiliza un modelo entrenado para responder preguntas en ese idioma.
"""

#CODIGO TERCER BLOQUE (QA)

from transformers import (
    AutoTokenizer,
    AutoModelForQuestionAnswering
)

import torch

# Seleccionar GPU o CPU
dispositivo_qa = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

nombre_modelo_qa = "distilbert-base-cased-distilled-squad"

# Descargar el tokenizador y el modelo directamente
tokenizador_qa = AutoTokenizer.from_pretrained(
    nombre_modelo_qa
)

modelo_qa = AutoModelForQuestionAnswering.from_pretrained(
    nombre_modelo_qa
)

modelo_qa.to(dispositivo_qa)
modelo_qa.eval()

print("Modelo de Question Answering cargado correctamente.")
print("Dispositivo utilizado:", dispositivo_qa)

def responder_pregunta_video(video_id, pregunta, cantidad_comentarios=5):
    """
    Responde una pregunta utilizando los comentarios con más likes
    del video seleccionado.
    """

    # Buscar el video
    registro_video = datos_youtube[
        datos_youtube["Video ID"] == video_id
    ]

    if registro_video.empty:
        return {
            "Error": "No se encontró el video solicitado."
        }

    # Seleccionar los comentarios con mayor cantidad de likes
    comentarios_video = (
        comentarios_limpios[
            comentarios_limpios["Video ID"] == video_id
        ]
        .sort_values("Likes", ascending=False)
        .head(cantidad_comentarios)
    )

    if comentarios_video.empty:
        return {
            "Error": "El video no tiene comentarios disponibles."
        }

    # Crear el contexto
    contexto = " ".join(
        comentarios_video["Comment"].astype(str).tolist()
    )

    # Tokenizar pregunta y contexto
    entradas = tokenizador_qa(
        pregunta,
        contexto,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    entradas = {
        nombre: tensor.to(dispositivo_qa)
        for nombre, tensor in entradas.items()
    }

    # Realizar inferencia
    with torch.no_grad():
        salida = modelo_qa(**entradas)

    probabilidades_inicio = torch.softmax(
        salida.start_logits,
        dim=-1
    )[0]

    probabilidades_fin = torch.softmax(
        salida.end_logits,
        dim=-1
    )[0]

    posicion_inicio = int(
        torch.argmax(probabilidades_inicio)
    )

    posicion_fin = int(
        torch.argmax(probabilidades_fin)
    )

    # Evitar una respuesta con posiciones inválidas
    if posicion_fin < posicion_inicio:
        posicion_fin = posicion_inicio

    tokens_respuesta = entradas["input_ids"][0][
        posicion_inicio:posicion_fin + 1
    ]

    respuesta = tokenizador_qa.decode(
        tokens_respuesta,
        skip_special_tokens=True
    )

    confianza = (
        probabilidades_inicio[posicion_inicio]
        * probabilidades_fin[posicion_fin]
    ).item()

    return {
        "Video ID": video_id,
        "Título": registro_video.iloc[0]["Title"],
        "Pregunta": pregunta,
        "Respuesta": respuesta,
        "Confianza": round(confianza, 4),
        "Comentarios utilizados": len(comentarios_video)
    }

video_ejemplo = datos_youtube.iloc[0]

resultado_qa = responder_pregunta_video(
    video_id=video_ejemplo["Video ID"],
    pregunta="What do viewers say about Apple Pay?"
)

print("RESULTADO DE QUESTION ANSWERING")
print("--------------------------------")

for clave, valor in resultado_qa.items():
    print(f"{clave}: {valor}")

"""## 📝 11. Summarization

La sumarización permite condensar un conjunto de comentarios en un texto breve que conserve las opiniones e ideas principales. En este ejercicio se utiliza Gemini para generar en español un resumen de los comentarios con mayor interacción de cada video.
"""

# Configuración de Gemini para el tercer bloque
!pip install -q google-genai

from google.colab import userdata
from google import genai

# Leer la clave guardada en los secretos de Colab
gemini_api_key = userdata.get("GEMINI_API_KEY")

if not gemini_api_key:
    raise ValueError(
        "No se encontró el secreto GEMINI_API_KEY en Google Colab."
    )

# Crear el cliente
client = genai.Client(api_key=gemini_api_key)

print("Cliente de Gemini configurado correctamente.")

import time
def resumir_comentarios_video(video_id, cantidad_comentarios=10):
    """
    Resume en español los comentarios con más likes de un video.
    """

    # Buscar información del video
    registro_video = datos_youtube[
        datos_youtube["Video ID"] == video_id
    ]

    if registro_video.empty:
        return {
            "Error": "No se encontró el video solicitado."
        }

    # Seleccionar comentarios con mayor interacción
    comentarios_video = (
        comentarios_limpios[
            comentarios_limpios["Video ID"] == video_id
        ]
        .sort_values("Likes", ascending=False)
        .head(cantidad_comentarios)
    )

    if comentarios_video.empty:
        return {
            "Error": "El video no tiene comentarios disponibles."
        }

    titulo = registro_video.iloc[0]["Title"]

    texto_comentarios = "\n".join(
        f"- {comentario}"
        for comentario in comentarios_video["Comment"].astype(str)
    )

    prompt_resumen = f"""
    Analiza los siguientes comentarios relacionados con el video
    titulado: "{titulo}".

    Genera un resumen en español de máximo 120 palabras.

    El resumen debe:
    1. Explicar la opinión general de los usuarios.
    2. Mencionar los aspectos positivos más frecuentes.
    3. Mencionar las críticas o preocupaciones.
    4. No inventar información que no aparezca en los comentarios.

    Comentarios:
    {texto_comentarios}
    """

    inicio = time.time()

    try:
        respuesta = client.models.generate_content(
            model="gemini-3.8-flash",
            contents=prompt_resumen
        )

        tiempo = time.time() - inicio

        return {
            "Video ID": video_id,
            "Título": titulo,
            "Comentarios utilizados": len(comentarios_video),
            "Resumen": respuesta.text,
            "Tiempo de respuesta": round(tiempo, 2),
            "Estado": "Exitoso"
        }

    except Exception as error:
        return {
            "Video ID": video_id,
            "Título": titulo,
            "Comentarios utilizados": len(comentarios_video),
            "Resumen": None,
            "Tiempo de respuesta": round(time.time() - inicio, 2),
            "Estado": "Fallido",
            "Error": str(error)
        }

resultado_resumen = resumir_comentarios_video(
    video_id=video_ejemplo["Video ID"],
    cantidad_comentarios=10
)

print("RESULTADO DE SUMMARIZATION")
print("--------------------------")

for clave, valor in resultado_resumen.items():
    print(f"\n{clave}:")
    print(valor)